#!/usr/bin/expect -f
set timeout 120
spawn rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" /home/anuhas/programming/smarttech-customization/supabase/functions/ root@178.104.127.220:/root/supabase/supabase/docker/volumes/functions/
expect "password:"
send "voibVmIdk9DqPMmZ\r"
expect eof
spawn rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" /home/anuhas/programming/smarttech-customization/supabase/functions/ root@178.104.127.220:/var/www/buildstart/supabase/functions/
expect "password:"
send "voibVmIdk9DqPMmZ\r"
expect eof
