#!/usr/bin/expect -f
set timeout 60
spawn scp -o StrictHostKeyChecking=no /home/anuhas/programming/smarttech-customization/supabase/functions/process-message/index.ts root@178.104.127.220:/root/supabase/supabase/docker/volumes/functions/process-message/index.ts
expect "password:"
send "voibVmIdk9DqPMmZ\r"
expect eof
spawn scp -o StrictHostKeyChecking=no /home/anuhas/programming/smarttech-customization/supabase/functions/process-message/index.ts root@178.104.127.220:/var/www/buildstart/supabase/functions/process-message/index.ts
expect "password:"
send "voibVmIdk9DqPMmZ\r"
expect eof
